import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const response = await fetch(
    `https://api.unsplash.com/photos/random/?client_id=${process.env.UNSPLASH_API_KEY}&query=nature&orientation=landscape`
  );
  const {
    urls: { full },
    description,
  } = await response.json();

  return (
    <html lang='en'>
      <body className={`relative min-h-screen ${inter.className}`}>
        <Image
          className='-z-50'
          alt={description}
          src={full}
          priority
          fill
          objectFit='cover'
          objectPosition='center'
        />
        {children}
      </body>
    </html>
  );
}
